pipeline {
    agent any

    environment {
        ENV_PATH = "/home/ubuntu/food_donation_env/.env"
        IMAGE_NAME = "food-donation-backend"
    }

    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'main', url: 'https://github.com/Atharv-code-bot/food_donation.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('backend/Donation/Donation') {
                    sh 'docker build -t ${IMAGE_NAME} .'
                }
            }
        }

        stage('Run Docker Container') {
            steps {
                dir('backend/Donation/Donation') {
                    sh 'docker stop ${IMAGE_NAME} || true'
                    sh 'docker rm ${IMAGE_NAME} || true'
                    sh 'docker run --env-file ${ENV_PATH} -d -p 8081:8080 --name ${IMAGE_NAME} ${IMAGE_NAME}'
                }
            }
        }
    }
}
